# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Link Issue to Pull Request

description: |
  This action links an issue to a pull request.

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5
      with:
        ignore-empty-workdir: true
        cache-dependency-glob: '${{ github.action_path}}/requirements.txt'

    - name: Link Issue to Pull Request
      shell: bash
      run: |
        uv venv .venv --python 3.12
        uv pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
        uv run ${SCRIPT_PATH}
      env:
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        SCRIPT_PATH: "${{ github.action_path }}/add_ref_to_issues_linked_to_pr.py"
        PYTHON_CMD: ${{ steps.setup-python.outputs.python-path }}
