# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Convert json file to matrix

description: |
  Convert json file to matrix

inputs:
  json-file-path:
    description: "Path of the json file"
    required: true
  download-json-file-from-artifact:
    description: "json file is available in the artifacts. The artifact name is the
      json-file-path without the .json extension."
    required: false
    default: 'false'

outputs:
  matrix:
    description: "Matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Get artifact name
      if: ${{ inputs.download-json-file-from-artifact == 'true' }}
      env:
        JSON_FILE_PATH: ${{ inputs.json-file-path }}
      shell: bash
      run: echo "JSON_ARTIFACT=${JSON_FILE_PATH} " | sed 's/\(.*\)\..*/\1/' >> $GITHUB_ENV

    - name: Download json artifact
      if: ${{ inputs.download-json-file-from-artifact == 'true' }}
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: ${{ env.JSON_ARTIFACT }}

    - name: Checkout repository
      if: ${{ inputs.download-json-file-from-artifact != 'true' }}
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        sparse-checkout: ${{ inputs.json-file-path }}
        sparse-checkout-cone-mode: false
        persist-credentials: false

    - name: Prepare matrix
      id: set-matrix
      shell: python
      run: |
        import json
        import os

        json_file = os.getenv('JSON_FILE')
        with open(json_file) as file:
          data = json.load(file)

        # filtering python version
        if os.getenv("PYTHON_VERSION"):
          data = [
            config for config in data
            if "python_versions" not in config or os.getenv("PYTHON_VERSION") in config["python_versions"]
          ]

        # get runner-name from environment variable
        for index, config in enumerate(data):
          data[index]["runner-name"] = (os.getenv(config["runner-name"], config["runner-name"])).strip()

        selected_flagship_products = os.getenv("SELECTED_FLAGSHIP_PRODUCTS", "")
        if selected_flagship_products != "":
          for index, config in enumerate(data):
            if config['pytest-markers'] != "":
              data[index]["pytest-markers"] = f"{config['pytest-markers']} and {selected_flagship_products}"
            else:
              data[index]["pytest-markers"] = selected_flagship_products

        matrix = {
          "config": data
        }

        output_file = os.getenv('GITHUB_OUTPUT')
        with open(output_file, "a") as file:
          file.write(f"matrix={json.dumps(matrix)}")
      env:
        JSON_FILE: ${{ inputs.json-file-path }}
