# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: _pre_certification_workflow

permissions: {}

on:
  workflow_call:
    inputs:
      tag-to-certify:
        type: string
        required: true
      python-version:
        description: >
          Python version to use. Use in nested workflows:
            build-wheel
            doc-build
        type: string
        required: true
      poetry-version:
        description: "Poetry version to use."
        required: true
        type: string
      wheel-base-artifact-name:
        description: >
          Base name of the wheel artifact. Use in nested workflows:
            build-wheel
        type: string
        required: true
      severity-level:
        description: "Severity level for the analysis"
        required: true
        type: string
      # Required with defaults
      poetry-parent-directory:
        description: >
          Parent directory for the poetry project. Use in nested workflows:
            build-wheel
            doc-build
        type: string
        default: '.'
      doc-directory:
        description: >
          Directory containing the documentation source files. Use in nested workflows:
            doc-build
        type: string
        default: 'doc'
      runner:
        description: >
          Runner label. Use in nested workflows:
            build-wheel
        type: string
        default: 'windows-latest'
      # Optional
      ref:
        description: >
          Reference to checkout. Default: github.ref. Use in nested workflows:
            build-wheel
            doc-build
        type: string
        required: false
        default: ''
      gh-pages-cname:
        description: >
          CNAME record for the gh-pages branch. Use in nested workflows:
            doc-build
        type: string
        required: false
        default: ''
      gh-pages-doc-artifact-name:
        description: >
          Name of the gh-pages documentation artifact name. Use in nested workflows:
            doc-build
        type: string
        required: false
        default: ''
      poetry-install-args:
        description: >
          Additional arguments for poetry install when building docs. Use in nested
          workflows:
            doc-build
        type: string
        required: false
        default: '--only doc -vv'
      env-vars:
        description: >
          Additional environment variables. Format: 'var-1: val-1\nvar-2: val-2' (YAML-like
          format). Use in nested workflows:
            doc-build
        type: string
        required: false
        default: ""
      run-compatibility-tests:
        description: "Run compatibility tests"
        required: false
        default: true
        type: boolean
      poetry-plugin-export-version:
        description: "Specific version for poetry-plugin-export."
        required: false
        type: string
        default: "1.9.0"
    outputs:
      commit-is-already-tagged:
        description: 'Commit is or is not tagged with the certification tag.'
        value: ${{ jobs.needs-certification.outputs.commit_is_already_tagged }}
      pre-certification-successfully-completed:
        description: 'Pre-certification is successful.'
        value: ${{ jobs.pre-certification-status.outputs.is_successful == 'true' }}
    secrets:
      READ_DEPENDABOT_ALERTS:
        description: "Token to read Dependabot alerts"
        required: true
      PYANSYS_PRIVATE_PYPI_PAT:
        description: "Personal Access Token for private PyPI"
        required: false
      PYANSYS_CI_BOT_TOKEN:
        description: "Token for the CI bot"
        required: false # to make it required when all saf repos are ready for it

env:
  POETRY_HTTP_BASIC_SOLUTIONS_PRIVATE_PYPI_USERNAME: "PAT"
  POETRY_HTTP_BASIC_SOLUTIONS_PRIVATE_PYPI_PASSWORD: ${{ secrets.PYANSYS_PRIVATE_PYPI_PAT
    }}
  POETRY_HTTP_BASIC_PYANSYS_PRIVATE_PYPI_USERNAME: "PAT"
  POETRY_HTTP_BASIC_PYANSYS_PRIVATE_PYPI_PASSWORD: ${{ secrets.PYANSYS_PRIVATE_PYPI_PAT}}

jobs:
  needs-certification:
    name: "Check for certification tag"
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - id: verify-tag
        uses: ansys/saf-devops/verify-tag-and-commit@v1
        with:
          tag: ${{ inputs.tag-to-certify }}
    outputs:
      commit_is_already_tagged: ${{ steps.verify-tag.outputs.commit-is-already-tagged
        }}

  actions-style:
    name: "Actions style checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read the workflow files in the project
    steps:
      - uses: ansys/actions/check-actions-security@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          generate-summary: true
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          auditing-level: 'high'
        # TODO: Review and adjust the continue-on-error behavior for actions style checks
        continue-on-error: true # To remove when all SAF repos are ready for it

  vulnerabilities:
    name: "Vulnerabilities"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read the dependencies and source code of the library
    steps:
      - uses: ansys/saf-devops/check-deps-vulnerabilities@v1
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
          poetry-install-args: '--all-extras'
          upgrade-pip: true
          max-allowed-severity: 'medium'
          poetry-plugin-export-version: ${{ inputs.poetry-plugin-export-version }}

  build-doc:
    permissions:
      contents: read # To read the repository content
    uses: ansys/saf-devops/.github/workflows/_doc_build.yml@v1
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}
      poetry-parent-directory: ${{ inputs.poetry-parent-directory }}
      doc-directory: ${{ inputs.doc-directory }}
      gh-pages-cname: ${{ inputs.gh-pages-cname }}
      gh-pages-doc-artifact-name: ${{ inputs.gh-pages-doc-artifact-name }}
      ref: ${{ inputs.ref }}
      poetry-install-args: ${{ inputs.poetry-install-args }}
      env-vars: ${{ inputs.env-vars }}
    secrets:
      PYANSYS_PRIVATE_PYPI_PAT: ${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}

  get-production-dependabot-alerts:
    permissions:
      contents: read
      security-events: read # For Dependabot alerts
    name: Get production Dependabot alerts
    runs-on: ubuntu-latest
    steps:
      - name: Get production dependencies
        uses: ansys/saf-devops/get-production-dependencies@v1
        with:
          poetry-version: ${{ inputs.poetry-version }}
          poetry-parent-directory: ${{ inputs.poetry-parent-directory }}
          python-version: ${{ inputs.python-version }}

      - name: Analyze Dependabot Alerts
        uses: ansys/saf-devops/analyze-dependabot-alerts@v1
        with:
          severity-level: ${{ inputs.severity-level }}
          manifest-path: ${{ inputs.poetry-parent-directory != '.' && format('{0}/',
            inputs.poetry-parent-directory) || '' }}poetry.lock
          read-dependabot-alerts-token: ${{ secrets.READ_DEPENDABOT_ALERTS }}

  sbom:
    name: Generate SBOM
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: generate sbom
        uses: ansys/saf-devops/generate-sbom@v1
        with:
          poetry-version: ${{ inputs.poetry-version }}

  pre-certification-status:
    name: Verify certification success
    needs:
      # TODO: Review and uncomment the following dependencies if needed
      # - actions-style
      # - vulnerabilities
      - build-doc
      - get-production-dependabot-alerts
      - sbom
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        shell: bash
        run: exit 1
    outputs:
      is_successful: ${{ (!contains(needs.*.result, 'failure') && !contains(needs.*.result,
        'cancelled')) && 'true' || 'false' }}
