# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: (repo) Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}
concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release-please:
    name: Release Please
    permissions:
      contents: write # Allows creating/updating files, tags, and releases in the repo
      pull-requests: write # Allows creating/updating/closing pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ github.token }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: true

      - name: Update Latest vX and vX.Y Tag
        uses: ansys/saf-devops/tag-repository-version@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          release-version: ${{ steps.release.outputs.tag_name }}
